package(default_visibility = ["//:__subpackages__"])

java_library(
    name = "EMapToMapConverter",
    srcs = [":EMapToMapConverter.java"],
    deps = [
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:org_eclipse_emf_org_eclipse_emf_common",
    ],
)

java_library(
    name = "StringToURIConverter",
    srcs = [":StringToURIConverter.java"],
    deps = [
        "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:org_eclipse_emf_org_eclipse_emf_common",
    ],
)
