name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('MODULE.bazel', 'maven_lock.json') }}
          restore-keys: ${{ runner.os }}-bazel-
      - run: make cd
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create Release
        run: gh release create ${{ github.ref_name }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ github.token }}
